### PR TITLE
Fixed Fluor doesn't function when Karabiner-Elements is active

### LINKED ISSUE #14: Fluor doesn't function when Karabiner-Elements is active
I believe the culprit here is something from the code you used from fntoggle, and as such may fall outside of your knowledge to fix, but I just wanted to make you aware that as stated in the title, Fluor simply doesn't function unless [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) is quit. I also opened an issue [there](https://github.com/tekezo/Karabiner-Elements/issues/579) in case @tekezo knows how to fix it.

### PR DESCRIPTION
**Pull request by snowfoxzx**
Fixed #14

### CODE REVIEW

**Comment by Pyroh** [comment]
I forgot about it sorry.
Seems ok for me, merged !

**Comment by Grogs** [comment]
Would love to get a build with this. I'll try and build from source for now.

**Comment by Pyroh** [comment]
The current code in `master` is broken I have to do some more work on it. The thing is that my everyday work take me a lot of time. I'll try to fix this by the end of the week.

**Comment by Grogs** [comment]
Ah, fair enough - no rush. Thanks for the app Pyroh, I find it very useful.

**Comment by edouardp** [comment]
Is there any chance of getting a new release of Fluor with this fix in it? I'm loving Fluor on my dev machine for running Windows VMs, but Karabiner is also a productivity boost for me, so I'd love to be able to use them together!

**Comment by Pyroh** [comment]
Yes it will be included in the upcoming 2.0 release I'm working on. Available when it's done since I've got really busy days at work.
You can follow me on Twitter I sometimes post dev news.

**Comment by remarkov** [comment]
Another anxious user of Karabiner-Elements and Fluor here... Wish they could work together! Hope you will find some time to make at least one more beta with this commit. Best of luck!

**Comment by Pyroh** [comment]
I cherry picked this commit and put it in the original `1.1` code. I made a new branch from it called `SpecialDev`. Clone it and compile it now or wait this evening (for me it's 8:11 AM here) for me to renew my Apple Dev subscription and to ship a *new* signed version of **Fluor**.

The version is labeled `1.2beta2`.

**Comment by remarkov** [comment]
Unfortunately I don't have XCode installed on my machine so can't compile it myself, so I'll wait, no problem. Btw, just followed you on Twitter :)

**Comment by Pyroh** [comment]
Go check the [release](https://github.com/Pyroh/Fluor/releases/tag/1.2beta2). Finally signed 😃

**Comment by remarkov** [comment]
Works perfectly, thanks a lot! Looking forward to seeing the 2.0 release.

**Pull request merged**
